version: '3.7'

services:
  master:
    image: citusdata/citus:12.1.3
    labels: ["com.citusdata.role=Master"]
    ports:
      - "5432:5432"
    environment: &AUTH
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repluser
      - POSTGRESQL_REPLICATION_PASSWORD=replpassword
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./db/backup:/backup
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  worker:
    image: citusdata/citus:12.1.3
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"

  manager:
    image: citusdata/membership-manager:0.3.0
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH

  rabbit:
    build:
      dockerfile: rabbit/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "5050:80"
    links:
      - "db-master"
    volumes:
      - ./db/backup:/backup
    logging:
      driver: none

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379

  backend:
    build:
      args:
        JAR_FILE: build/libs/socialnetwork-1.0.jar
    ports:
      - "8080:8080"
    depends_on:
      db-master:
        condition: service_healthy
      db-slave-1:
        condition: service_healthy
      db-slave-2:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-master:5432/sn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=rmuser
      - RABBIT_PASSWORD=rmpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379